version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]
  environment = [
    "nodejs",
    "browser"
  ]
  style_guide = "standard"

[[transformers]]
name = "standardjs"
enabled = true